services:

  # ExceptionLogger: errors channel
  olml89\TelegramUserbot\Backend\Shared\Infrastructure\Symfony\Exception\ExceptionLogger:
    arguments:
      $logger: '@monolog.logger.errors'

  # Don't register ExceptionSentryReporterSubscriber
  olml89\TelegramUserbot\Backend\Shared\Infrastructure\Symfony\EventSubscribers\ExceptionSentryReporterSubscriber:
    autowire: false
    autoconfigure: false
    public: false

  # ApiExceptionResponseMapper
  olml89\TelegramUserbot\Backend\Shared\Infrastructure\Symfony\Exception\ApiExceptionResponseMapper:
    arguments:
      $debug: '%kernel.debug%'
      $exceptionChainBuilder: '@olml89\TelegramUserbot\Backend\Shared\Domain\Exception\ExceptionChainBuilder'

  # CaughtExceptionHandler: logs to the errors channel
  olml89\TelegramUserbot\Backend\Shared\Domain\Exception\Handler\CaughtExceptionHandler:
    arguments:
      $exceptionHandlers:
        - '@olml89\TelegramUserbot\Backend\Shared\Infrastructure\Symfony\Exception\ExceptionLogger'
