[program:phone-login]
command=/usr/local/bin/php /telegram-userbot/bot/bin/action/phone-login.php

# Don't start with the container, start and stop as demanded
autostart=false
autorestart=false

# Don't wait for process to reach RUNNING state; consider it started immediately
startsecs=0

# Forward logs directly to container streams for docker to capture
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

stopsignal=TERM
stopasgroup=true
killasgroup=true
