name: telegram-userbot

services:

  # Infrastructure layers
  alloy:
    container_name: telegram_userbot_alloy
    command: [run, /etc/alloy/config.alloy]
    networks:
      - telegram-userbot-grafana-network

  redis:
    container_name: telegram_userbot_redis
    depends_on:
      alloy:
        condition: service_started
    command: [redis-server, /usr/local/etc/redis/redis.conf]
    networks:
      - telegram-userbot-network

  postgres:
    container_name: telegram_userbot_postgres
    depends_on:
      alloy:
        condition: service_started
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: [-c, config_file=/etc/postgresql/postgresql.conf]
    networks:
      - telegram-userbot-network

  # Application layers
  bot:
    container_name: telegram_userbot_bot
    depends_on:
      alloy:
        condition: service_started
      redis:
        condition: service_started
      postgres:
        condition: service_started
    healthcheck:
      # Wait until the 9001 port is responsive, meaning supervisor is already running
      test: [CMD, nc, -z, 0.0.0.0, '9001']
      interval: 5s
      timeout: 10s
      retries: 50
    environment:
      APP_ENV: ${APP_ENV}
      SUPERVISOR_USER: ${SUPERVISOR_USER}
      SUPERVISOR_PASSWORD: ${SUPERVISOR_PASSWORD}
    tty: true
    entrypoint: [sh, bin/entrypoint.sh]
    networks:
      - telegram-userbot-network

  bot-manager:
    container_name: telegram_userbot_bot_manager
    depends_on:
      alloy:
        condition: service_started
      redis:
        condition: service_started
      bot:
        condition: service_healthy
    healthcheck:
      # Wait until the 8080 port is responsive, meaning the websocket server is already running
      test: [CMD, nc, -z, 0.0.0.0, '8080']
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      APP_ENV: ${APP_ENV}
      SUPERVISOR_USER: ${SUPERVISOR_USER}
      SUPERVISOR_PASSWORD: ${SUPERVISOR_PASSWORD}
    tty: true
    entrypoint: [sh, bin/entrypoint.sh]
    networks:
      - telegram-userbot-network

  backend:
    container_name: telegram_userbot_backend
    depends_on:
      alloy:
        condition: service_started
      postgres:
        condition: service_started
      bot-manager:
        condition: service_healthy
    healthcheck:
      # Wait until the 9000 port is responsive, meaning the php-fpm is already running.
      test: [CMD, nc, -zv, 127.0.0.1, '9000']
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      APP_ENV: ${APP_ENV}
    entrypoint: [sh, bin/entrypoint.sh]
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - telegram-userbot-network

  tusd:
    container_name: telegram_userbot_tusd
    image: tusproject/tusd:latest
    depends_on:
      alloy:
        condition: service_started
    healthcheck:
      # Wait until the 8080 port is responsive, meaning the tusd server is already running
      test: [CMD, nc, -z, localhost, '8080']
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - -base-path=/tus/uploads
      - -upload-dir=/var/uploads
      - -hooks-http=http://nginx/api/files/validation
      - -hooks-enabled-events=pre-create
      - -behind-proxy
    networks:
      - telegram-userbot-network

  nginx:
    container_name: telegram_userbot_nginx
    depends_on:
      alloy:
        condition: service_started
      tusd:
        condition: service_healthy
      bot-manager:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT}:80
    networks:
      - telegram-userbot-network

  # Monitoring layers
  loki:
    container_name: telegram_userbot_loki
    depends_on:
      alloy:
        condition: service_started
    command: [-config.file=/etc/loki/local-config.yaml]
    networks:
      - telegram-userbot-grafana-network

  grafana:
    container_name: telegram_userbot_grafana
    depends_on:
      alloy:
        condition: service_started
      loki:
        condition: service_started
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECURITY_ADMIN_PASSWORD}
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - telegram-userbot-grafana-network

volumes:
  telegram-userbot-db:
  telegram-userbot-redis:
  telegram-userbot-loki:

networks:
  telegram-userbot-network:
  telegram-userbot-grafana-network:
