services:

  ######################################################################################################################
  # Infrastructure layer
  ######################################################################################################################

  alloy:
    build:
      context: .
      dockerfile: alloy/Dockerfile
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy:cached

  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
      target: dev
    volumes:
      - telegram-userbot-redis:/data:cached
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:cached

  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
      target: dev
    # Expose the database port to the outside: only during development
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - telegram-userbot-postgres:/var/lib/postgresql/data:cached
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:cached

  ######################################################################################################################
  # Application layer
  ######################################################################################################################

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BOT_PORT}
    entrypoint: [/usr/local/bin/bot-entrypoint]
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
      COMPOSER_HOME: var/composer
    user: ${UID}:${GID}
    volumes:
      #Executables
      - ./dev/bin/composer/composer-install:/usr/local/bin/composer-install:cached
      - ./bot/docker/bot-entrypoint:/usr/local/bin/bot-entrypoint:cached
      #Configuration
      - ./bot/docker/supervisor:/etc/supervisor:cached
      # Source code
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot:/telegram-userbot/bot:cached

  bot-manager:
    build:
      context: .
      dockerfile: bot-manager/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BOT_MANAGER_PORT}
    entrypoint: [/usr/local/bin/bot-manager-entrypoint]
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
      COMPOSER_HOME: var/composer
    user: ${UID}:${GID}
    volumes:
      # Executables
      - ./dev/bin/composer/composer-install:/usr/local/bin/composer-install:cached
      - ./bot-manager/docker/bot-manager-entrypoint:/usr/local/bin/bot-manager-entrypoint:cached
      # Configuration
      - ./bot-manager/docker/supervisor:/etc/supervisor:cached
      # Source code
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot-manager:/telegram-userbot/bot-manager:cached

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BACKEND_PORT}
    entrypoint: [/usr/local/bin/backend-entrypoint]
    command:
      - php-fpm
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
      COMPOSER_HOME: var/composer
    user: ${UID}:${GID}
    volumes:
      # Executables
      - ./dev/bin/composer/composer-install:/usr/local/bin/composer-install:cached
      - ./backend/docker/backend-entrypoint:/usr/local/bin/backend-entrypoint:cached
      # Configuration
      - ./backend/docker/php-fpm/www.dev.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      # Source code
      - ./application:/telegram-userbot/application:cached
      - ./backend:/telegram-userbot/backend:cached
      # Runtime directories
      - ./.runtime/uploads:/telegram-userbot/backend/var/uploads:cached
      - ./.runtime/contents:/telegram-userbot/backend/var/contents:cached

  ######################################################################################################################
  # Gateway layer
  ######################################################################################################################

  tusd:
    build:
      context: .
      dockerfile: tusd/Dockerfile
      target: dev
    user: ${UID}:${GID}
    volumes:
      - ./.runtime/uploads:/srv/tusd-data/data:cached

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      target: dev
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached

  ######################################################################################################################
  # Monitoring layer
  ######################################################################################################################

  loki:
    build:
      context: .
      dockerfile: loki/Dockerfile
      target: dev
    volumes:
      - telegram-userbot-loki:/loki
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    build:
      context: .
      dockerfile: prometheus/Dockerfile
      target: dev
    volumes:
      - telegram-userbot-prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:cached

  grafana:
    build:
      context: .
      dockerfile: grafana/Dockerfile
      target: dev
    volumes:
      - ./grafana/dev:/etc/grafana/provisioning/datasources:cached

  ######################################################################################################################
  # Development layer
  ######################################################################################################################

  # Vite server for Hot Module Replacement
  vite:
    container_name: telegram_userbot_vite
    build:
      context: .
      dockerfile: vite/Dockerfile
    depends_on:
      alloy:
        condition: service_started
      backend:
        condition: service_healthy
    entrypoint: [/usr/local/bin/vite-entrypoint]
    command:
      - --
      - --host
      - 0.0.0.0
      - --port
      - "5173"
    environment:
      NPM_CONFIG_CACHE: var/npm
    ports:
      - ${VITE_PORT}:5173
    user: ${UID}:${GID}
    volumes:
      # Executables
      - ./vite/docker/vite-entrypoint:/usr/local/bin/vite-entrypoint:cached
      # Source code
      - ./backend:/telegram-userbot/backend:cached
      - ./vite:/telegram-userbot/vite:cached

  # dev container to run code quality tools
  dev:
    container_name: telegram_userbot_dev
    build:
      context: .
      dockerfile: dev/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_DEV_PORT}
    depends_on:
      alloy:
        condition: service_started
      backend:
        condition: service_healthy
    cpus: 12
    mem_limit: 24g
    tty: true
    entrypoint: [/usr/local/bin/dev-entrypoint]
    environment:
      APP_ENV: ${APP_ENV}
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
      COMPOSER_PROCESS_TIMEOUT: 0
      NPM_CONFIG_CACHE: var/npm
      HOME: /home/${USER}
      COMPOSER_HOME: var/composer
    user: ${UID}:${GID}
    volumes:
      # Executables
      - ./dev/bin/composer/composer-install:/usr/local/bin/composer-install:cached
      - ./dev/docker/dev-entrypoint:/usr/local/bin/dev-entrypoint:cached
      # Git: use the host's git config
      - /home/${USER}:/home/${USER}:cached
      - ./.git:/telegram-userbot/.git:cached
      # Source code
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot:/telegram-userbot/bot:cached
      - ./bot-manager:/telegram-userbot/bot-manager:cached
      - ./backend:/telegram-userbot/backend:cached
      - ./dev:/telegram-userbot/dev:cached
