services:

  #Infrastructure layers
  alloy:
    build:
      dockerfile: alloy/Dockerfile
      target: dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./alloy/config.alloy:/etc/alloy/config.alloy:cached

  redis:
    build:
      dockerfile: redis/Dockerfile
      target: dev
    volumes:
      - telegram-userbot-redis:/data:cached
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:cached

  postgres:
    build:
      dockerfile: postgres/Dockerfile
      target: dev
    ports: # Expose the database port to the outside: only during development
      - ${POSTGRES_PORT}:${DB_PORT}
    volumes:
      - telegram-userbot-db:/var/lib/postgresql/data:cached
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:cached

  # Application layers
  bot:
    build:
      dockerfile: bot/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BOT_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    user: ${UID}:${GID}
    volumes:
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot:/telegram-userbot/bot:cached
      - ./bot/supervisor:/etc/supervisor:cached
      - ./dev/bin/composer/composer-install.sh:/telegram-userbot/dev/bin/composer/composer-install.sh:cached

  bot-manager:
    build:
      dockerfile: bot-manager/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BOT_MANAGER_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    user: ${UID}:${GID}
    volumes:
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot-manager:/telegram-userbot/bot-manager:cached
      - ./bot-manager/supervisor:/etc/supervisor:cached
      - ./dev/bin/composer/composer-install.sh:/telegram-userbot/dev/bin/composer/composer-install.sh:cached

  backend:
    build:
      dockerfile: ./backend/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_BACKEND_PORT}
    environment:
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
    user: ${UID}:${GID}
    volumes:
      - ./application:/telegram-userbot/application:cached
      - ./backend:/telegram-userbot/backend:cached
      - ./backend/php-fpm/www.dev.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ./dev/bin/composer/composer-install.sh:/telegram-userbot/dev/bin/composer/composer-install.sh:cached
      - ./.runtime/uploads:/var/uploads:cached
      - ./.runtime/content:/var/content:cached

  tusd:
    user: ${UID}:${GID}
    volumes:
      - ./.runtime/uploads:/var/uploads:cached

  nginx:
    build:
      dockerfile: nginx/Dockerfile
      target: dev
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:cached

  # Monitoring layers
  loki:
    build:
      dockerfile: loki/Dockerfile
      target: dev
    volumes:
      - telegram-userbot-loki:/loki
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml

  grafana:
    build:
      dockerfile: grafana/Dockerfile
      target: dev
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:cached

  # Vite server for Hot Module Replacement
  vite:
    container_name: telegram_userbot_vite
    build:
      dockerfile: vite/Dockerfile
    depends_on:
      alloy:
        condition: service_started
      backend:
        condition: service_healthy
    entrypoint: [sh, /telegram-userbot/vite/entrypoint.sh]
    environment:
      NPM_CONFIG_CACHE: /telegram-userbot/vite/var/npm
    ports:
      - ${VITE_PORT}:5173
    user: ${UID}:${GID}
    volumes:
      - ./backend:/telegram-userbot/backend:cached
      - ./vite:/telegram-userbot/vite:cached

  # dev container to run code quality tools
  dev:
    container_name: telegram_userbot_dev
    depends_on:
      alloy:
        condition: service_started
      backend:
        condition: service_healthy
    build:
      dockerfile: dev/Dockerfile
      target: dev
      args:
        XDEBUG_PORT: ${XDEBUG_DEV_PORT}
    cpus: 12
    mem_limit: 24g
    tty: true
    entrypoint: [sh, bin/entrypoint.sh]
    environment:
      APP_ENV: ${APP_ENV}
      PHP_IDE_CONFIG: "serverName=${PHP_SERVER_NAME}"
      COMPOSER_PROCESS_TIMEOUT: 0
    user: ${UID}:${GID}
    volumes:
      - ./.git:/telegram-userbot/.git:cached
      - ./application:/telegram-userbot/application:cached
      - ./bot-runtime:/telegram-userbot/bot-runtime:cached
      - ./bot:/telegram-userbot/bot:cached
      - ./bot-manager:/telegram-userbot/bot-manager:cached
      - ./backend:/telegram-userbot/backend:cached
      - ./dev:/telegram-userbot/dev:cached
