<?php

declare(strict_types=1);

namespace olml89\TelegramUserbot\Backend\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260202105520 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Convert File in a first citizen entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE files (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                public_id UUID NOT NULL, 
                name VARCHAR(50) NOT NULL, 
                original_name VARCHAR(255) NOT NULL, 
                mime_type VARCHAR(100) NOT NULL, 
                bytes BIGINT NOT NULL, 
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_6354059B5B48B91 ON files (public_id)
        ');
        $this->addSql('
            ALTER TABLE contents DROP file_name
        ');
        $this->addSql('
            ALTER TABLE contents DROP file_original_name
        ');
        $this->addSql('
            ALTER TABLE contents DROP file_mime_type
        ');
        $this->addSql('
            ALTER TABLE contents DROP file_size
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('
            DROP TABLE files
        ');
        $this->addSql('
            ALTER TABLE contents ADD file_name VARCHAR(50) NOT NULL
        ');
        $this->addSql('
            ALTER TABLE contents ADD file_original_name VARCHAR(255) NOT NULL
        ');
        $this->addSql('
            ALTER TABLE contents ADD file_mime_type VARCHAR(100) NOT NULL
        ');
        $this->addSql('
            ALTER TABLE contents ADD file_size INT NOT NULL
        ');
    }
}
