<?php

declare(strict_types=1);

namespace olml89\TelegramUserbot\Backend\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260507160210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add a content_files table to hold the relationship between contents and files (make files agnostic of contents)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE content_files (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                public_id UUID NOT NULL, 
                content_id INT NOT NULL, 
                file_id INT NOT NULL, 
                created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
                updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
                PRIMARY KEY (id))
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_EDF6148BB5B48B91 
            ON content_files (public_id)
        ');
        $this->addSql('
            CREATE INDEX IDX_EDF6148B84A0A3ED 
            ON content_files (content_id)
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_EDF6148B93CB796C 
            ON content_files (file_id)
        ');
        $this->addSql('
            ALTER TABLE content_files 
            ADD CONSTRAINT FK_EDF6148B93CB796C 
            FOREIGN KEY (file_id) REFERENCES files (id)
        ');
        $this->addSql('
            ALTER TABLE content_files 
            ADD CONSTRAINT FK_EDF6148B84A0A3ED 
            FOREIGN KEY (content_id) REFERENCES contents (id)
        ');
        $this->addSql('
            ALTER TABLE files 
            DROP CONSTRAINT fk_635405984a0a3ed
        ');
        $this->addSql('
            DROP INDEX idx_635405984a0a3ed
        ');
        $this->addSql('
            ALTER TABLE files 
            DROP content_id
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('
            ALTER TABLE content_files 
            DROP CONSTRAINT FK_EDF6148B93CB796C
        ');
        $this->addSql('
            ALTER TABLE content_files 
            DROP CONSTRAINT FK_EDF6148B84A0A3ED
        ');
        $this->addSql('
            DROP TABLE content_files
        ');
        $this->addSql('
            ALTER TABLE files 
            ADD content_id INT DEFAULT NULL
        ');
        $this->addSql('
            ALTER TABLE files 
            ADD CONSTRAINT fk_635405984a0a3ed 
            FOREIGN KEY (content_id) REFERENCES contents (id) 
            ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE
        ');
        $this->addSql('
            CREATE INDEX idx_635405984a0a3ed 
            ON files (content_id)
        ');
    }
}
