<?php

declare(strict_types=1);

namespace olml89\TelegramUserbot\Backend\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127024730 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add domain events recording';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE events (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                public_id UUID NOT NULL, 
                event_class VARCHAR(255) NOT NULL, 
                entity_class VARCHAR(255) NOT NULL, 
                entity_id INT NOT NULL, 
                payload JSON NOT NULL, 
                occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_5387574AB5B48B91 ON events (public_id)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('
            DROP TABLE events
        ');
    }
}
