<?php

declare(strict_types=1);

namespace olml89\TelegramUserbot\Backend\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260126124440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add contents persistence';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE contents (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                public_id UUID NOT NULL, 
                name VARCHAR(255) NOT NULL, 
                description TEXT DEFAULT NULL, 
                tags JSON NOT NULL, 
                file_name VARCHAR(50) NOT NULL, 
                file_original_name VARCHAR(255) NOT NULL, 
                file_mime_type VARCHAR(100) NOT NULL, 
                file_size INT NOT NULL, 
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_B4FA1177B5B48B91 ON contents (public_id)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('
            DROP TABLE contents
        ');
    }
}
