<?php

declare(strict_types=1);

namespace olml89\TelegramUserbot\Backend\Infrastructure\Doctrine\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260203185117 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tags';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE tags (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                public_id UUID NOT NULL, 
                name VARCHAR(50) NOT NULL, 
                PRIMARY KEY (id)
            )
        ');
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_6FBC9426B5B48B91 
            ON tags (public_id)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('
            DROP TABLE tags
        ');
    }
}
