monolog:
  channels:
    - app
    - warnings
    - errors

  handlers:

    # Main app logger (debug, info, notice)
    # It is also the default channel, as it is the first one defined
    app:
      type: stream
      path: php://stdout
      level: debug
      channels:
        - app
      formatter: monolog.formatter.json

    warnings:
      type: stream
      path: php://stderr
      level: warning
      max_level: warning
      channels:
        - warnings
      formatter: monolog.formatter.json

    # Error logger (error, critical, alert, emergency)
    errors:
      type: stream
      path: php://stderr
      level: error
      channels:
        - errors
      formatter: monolog.formatter.json
