name: telegram-userbot
services:
  nginx:
    image: nginx:stable-alpine
    container_name: telegram_userbot_nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/telegram-userbot
    networks:
      - telegram-userbot-network
  php-fpm:
    build:
      dockerfile: ./php-fpm/Dockerfile
      target: prod
    container_name: telegram_userbot_app
    volumes:
      - ../:/telegram-userbot
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - telegram-userbot-network
  postgres:
    image: postgres:17-alpine
    container_name: telegram_userbot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${DB_PORT}
    volumes:
      - telegram-userbot-db:/var/lib/postgresql/data
    networks:
      - telegram-userbot-network
volumes:
  telegram-userbot-db:
networks:
  telegram-userbot-network:
