name: Deploy

# Waits for the CI workflow to complete successfully before deploying

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
  workflow_dispatch:  # Allows manual deployment
    inputs:
      branch:
        required: true
        description: 'Branch to deploy'
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push'
      )
    environment: staging

    env:
      BRANCH: ${{ github.event.inputs.branch || github.event.workflow_run.head_branch || 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Generate .env file
        run: |
          # Stop script if any variable is missing instead of failing silently
          set -euo pipefail
          
          cat << EOF > .env
            # HTTPS variables
            LETSENCRYPT_EMAIL=${{ vars.LETSENCRYPT_EMAIL }}
            HTTPS_PORT=${{ vars.HTTPS_PORT }}
          
            # .env variables
            APP_ENV=${{ vars.APP_ENV }}
            HTTP_PORT=${{ vars.HTTP_PORT }}
            GRAFANA_SECURITY_ADMIN_PASSWORD=${{ secrets.GRAFANA_SECURITY_ADMIN_PASSWORD }}

            # backend/.env variables
            APP_DEBUG=${{ vars.APP_DEBUG }}
            APP_SECRET=${{ secrets.APP_SECRET }}
            BACKEND_SENTRY_DSN=${{ secrets.BACKEND_SENTRY_DSN }}
            DB_NAME=${{ vars.DB_NAME }}
            DB_USER=${{ vars.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            APP_LIBRARY_CONTENT_PER_PAGE=${{ vars.APP_LIBRARY_CONTENT_PER_PAGE }}

            # bot/.env variables
            BOT_SENTRY_DSN=${{ secrets.BOT_SENTRY_DSN }}
            TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}
            TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}
            TELEGRAM_PHONE_NUMBER=${{ secrets.TELEGRAM_PHONE_NUMBER }}
            TELEGRAM_USERNAME=${{ secrets.TELEGRAM_USERNAME }}

            # Export bot-manager/.env variables
            BOT_MANAGER_SENTRY_DSN=${{ secrets.BOT_MANAGER_SENTRY_DSN }}

            # Export bot-runtime/.env variables
            REDIS_STATUS_CHANNEL=${{ vars.REDIS_STATUS_CHANNEL }}
            REDIS_PHONE_CODE_STORAGE_KEY=${{ vars.REDIS_PHONE_CODE_STORAGE_KEY }}
            SUPERVISOR_CONFIG_PATH=${{ vars.SUPERVISOR_CONFIG_PATH }}
            SUPERVISOR_USER=${{ vars.SUPERVISOR_USER }}
            SUPERVISOR_PASSWORD=${{ secrets.SUPERVISOR_PASSWORD }}
          EOF
          
          # Set permissions to .env file Only the owner can read or write
          chmod 600 .env

      - name: Upload .env to the server and remove it
        run: |
          trap 'rm -f .env' EXIT
          
          scp \
            -i ~/.ssh/deploy_key \
            -P ${{ vars.SSH_PORT }} \
            .env \
            ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/home/tbot/telegram-userbot/.env

      - name: Run deploy script in the server using the specified branch
        run: |
          ssh \
            -i ~/.ssh/deploy_key \
            -p ${{ vars.SSH_PORT }} \
            ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << EOF
              cd /home/tbot/telegram-userbot
              chmod 600 .env
              just deploy "${{ env.BRANCH }}"           
            EOF
