name: PHP Mess Detector

on: [push]

jobs:
  phpmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.4.0

      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: Run PHPMD
        uses: php-actions/phpmd@v1.0.0
        with:
          version: composer
          php_version: 8.4
          path: src/,tests/
          output: text
          ruleset: ruleset.xml
