name: Pint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Wait for GHCR to complete if it's running
  wait-for-image:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GHCR workflow
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'build-and-push'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped

  pint:
    needs: wait-for-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run code linting (pint) in the dev container
        run: |
          docker run --rm \
            -e APP_ENV=ci \
            -w /telegram-userbot/dev \
            ghcr.io/olml89/telegram-userbot-dev:ci \
            ./pint/pint.sh --test
